// Payment Service - Handles Stripe, Przelewy24, BLIK payments
// This is a MOCK implementation for the frontend prototype
// In production, actual API calls would be made to payment providers

const PAYMENT_METHODS = {
  STRIPE: 'stripe',
  PRZELEWY24: 'przelewy24',
  BLIK: 'blik'
};

// Simulate payment processing delay
const simulateDelay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

// Generate unique payment ID
const generatePaymentId = () => `PAY-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;

// Stripe Payment (Card)
export const processStripePayment = async (orderData, cardDetails) => {
  console.log('Processing Stripe payment...', { orderData, cardDetails: '***' });
  
  await simulateDelay(2000);
  
  // Simulate successful payment (90% success rate for demo)
  const success = Math.random() > 0.1;
  
  if (success) {
    return {
      success: true,
      paymentId: generatePaymentId(),
      method: PAYMENT_METHODS.STRIPE,
      amount: orderData.total,
      currency: 'PLN',
      status: 'completed',
      timestamp: new Date().toISOString(),
      receipt: {
        cardLast4: cardDetails?.cardNumber?.slice(-4) || '4242',
        cardBrand: 'Visa'
      }
    };
  } else {
    return {
      success: false,
      error: 'Płatność odrzucona przez bank. Spróbuj ponownie.',
      errorCode: 'CARD_DECLINED'
    };
  }
};

// Przelewy24 Payment
export const processPrzelewy24Payment = async (orderData, bankCode) => {
  console.log('Processing Przelewy24 payment...', { orderData, bankCode });
  
  await simulateDelay(1500);
  
  // In production, this would redirect to P24 payment page
  // For demo, we simulate the payment URL
  const paymentUrl = `https://secure.przelewy24.pl/demo?order=${orderData.orderId}&amount=${orderData.total}`;
  
  return {
    success: true,
    paymentId: generatePaymentId(),
    method: PAYMENT_METHODS.PRZELEWY24,
    amount: orderData.total,
    currency: 'PLN',
    status: 'pending',
    redirectUrl: paymentUrl,
    timestamp: new Date().toISOString()
  };
};

// BLIK Payment
export const processBlikPayment = async (orderData, blikCode) => {
  console.log('Processing BLIK payment...', { orderData, blikCode: '***' });
  
  // Validate BLIK code format (6 digits)
  if (!/^\d{6}$/.test(blikCode)) {
    return {
      success: false,
      error: 'Nieprawidłowy kod BLIK. Wprowadź 6 cyfr.',
      errorCode: 'INVALID_BLIK_CODE'
    };
  }
  
  await simulateDelay(3000);
  
  // Simulate successful payment (95% success rate for BLIK)
  const success = Math.random() > 0.05;
  
  if (success) {
    return {
      success: true,
      paymentId: generatePaymentId(),
      method: PAYMENT_METHODS.BLIK,
      amount: orderData.total,
      currency: 'PLN',
      status: 'completed',
      timestamp: new Date().toISOString()
    };
  } else {
    return {
      success: false,
      error: 'Kod BLIK wygasł lub został odrzucony. Wygeneruj nowy kod.',
      errorCode: 'BLIK_EXPIRED'
    };
  }
};

// Telegram Payment (using Telegram's built-in payments)
export const processTelegramPayment = async (orderData, webApp) => {
  console.log('Processing Telegram payment...', orderData);
  
  if (!webApp?.openInvoice) {
    return {
      success: false,
      error: 'Płatności Telegram niedostępne poza aplikacją Telegram.',
      errorCode: 'NOT_IN_TELEGRAM'
    };
  }
  
  // In production, the invoice URL would be generated by the backend
  // using Telegram Bot API's createInvoiceLink method
  const invoiceUrl = `https://t.me/$prascy_bot?startattach=pay_${orderData.orderId}`;
  
  try {
    const status = await webApp.openInvoice(invoiceUrl);
    
    if (status === 'paid') {
      return {
        success: true,
        paymentId: generatePaymentId(),
        method: 'telegram',
        amount: orderData.total,
        currency: 'PLN',
        status: 'completed',
        timestamp: new Date().toISOString()
      };
    } else {
      return {
        success: false,
        error: 'Płatność anulowana.',
        errorCode: 'PAYMENT_CANCELLED'
      };
    }
  } catch (error) {
    return {
      success: false,
      error: 'Błąd płatności Telegram.',
      errorCode: 'TELEGRAM_ERROR'
    };
  }
};

// Verify payment status
export const verifyPaymentStatus = async (paymentId) => {
  await simulateDelay(500);
  
  // In production, this would check the actual payment status
  return {
    paymentId,
    status: 'completed',
    verified: true
  };
};

// Create order with payment
export const createOrderWithPayment = async (orderData, paymentMethod, paymentDetails, webApp = null) => {
  const orderId = `ORD-${Date.now().toString().slice(-6)}`;
  
  const orderPayload = {
    ...orderData,
    orderId
  };
  
  let paymentResult;
  
  switch (paymentMethod) {
    case PAYMENT_METHODS.STRIPE:
      paymentResult = await processStripePayment(orderPayload, paymentDetails);
      break;
    case PAYMENT_METHODS.PRZELEWY24:
      paymentResult = await processPrzelewy24Payment(orderPayload, paymentDetails?.bankCode);
      break;
    case PAYMENT_METHODS.BLIK:
      paymentResult = await processBlikPayment(orderPayload, paymentDetails?.blikCode);
      break;
    case 'telegram':
      paymentResult = await processTelegramPayment(orderPayload, webApp);
      break;
    default:
      return {
        success: false,
        error: 'Nieznana metoda płatności.'
      };
  }
  
  if (paymentResult.success) {
    return {
      success: true,
      orderId,
      payment: paymentResult,
      order: {
        id: orderId,
        ...orderData,
        status: paymentResult.status === 'completed' ? 'payment_confirmed' : 'pending_payment',
        paymentId: paymentResult.paymentId,
        createdAt: new Date().toISOString()
      }
    };
  }
  
  return {
    success: false,
    orderId,
    error: paymentResult.error,
    errorCode: paymentResult.errorCode
  };
};

export default {
  processStripePayment,
  processPrzelewy24Payment,
  processBlikPayment,
  processTelegramPayment,
  verifyPaymentStatus,
  createOrderWithPayment,
  PAYMENT_METHODS
};
